name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    run-on: macos-12.5.1
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{matrix.mode-version}}
        uses: actions/setup/setup-node@v1
        with:
          node-version: ${{matrix.mode-version}}
            - name: install modules
              run: npm install




