name: linting, testing, building
on:
  push:
    branches: [ master, develop-module-fix ]
  pull_request:
    branches: [ master, develop-module-fix  ]
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build-and-ui-testing:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci --force
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: build storybook
        run: npm run build:storybook
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()

  checks:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [ 16.x ]
  steps:
    - uses: actions/checkout@v2
    - name: Staring Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm ci --force
    - name: linting typescript
      run: npm run lint:ts
      if: always()
    - name: linting css
      run: npm run stylelint:scss
      if: always()
    - name: unit testing
      run: npm run test
      if: always()



